defaults: &defaults
  help_link: "http://www.railstutorial.org/help"
  book_link: "http://www.railstutorial.org/book"
  gravatar_link: "http://gravatar.com/emails"
  email_from: "noreply@example.com"
  user:
    max_name_length: 50
    max_email_length: 255
    birthday_year_limit: 100
    min_password_length: 6
    items_per_page: 20
    gravatar_size: 80
    gravatar_link: "http://gravatar.com/emails"
    password_reset_expiration: 2 # in hours
  date_formats:
    user_profile: "%B %d, %Y"
  remember_me_enabled: 1
  micropost:
    max_content_length: 140
    max_image_size: 5 # in MB
    display_size: [300, 300] 
    image_types: ["image/jpeg", "image/gif", "image/png"]
    accept_types: "image/jpeg,image/gif,image/png"
